#!/usr/bin/perl

use strict;
use File::Copy;
use File::Path;

unlink "graphicssvs.zip";
rmtree "temp";
mkpath "temp/graphicssvs/graphics/general";
mkpath "temp/graphicssvs/winscw_udeb";
mkpath "temp/graphicssvs/graphics/bitgdi/general";
mkpath "temp/graphicssvs/graphics/fntstore/general";
mkpath "temp/graphicssvs/graphics/t_fbservapi/general";
mkpath "temp/graphicssvs/graphics/wserv/general";

my $epoc=$ENV{'EPOCROOT'} . "epoc32/";
copy("test.xml",                                                          "temp/test.xml");

copy $epoc . "release/winscw/udeb/twsgraphicshare.exe",                                                     "temp/graphicssvs/winscw_udeb/twsgraphicshare.exe";
copy $epoc . "release/winscw/udeb/twsgraphicunshare.exe",                                                   "temp/graphicssvs/winscw_udeb/twsgraphicunshare.exe";
copy $epoc . "release/winscw/udeb/t_animplugin.dll",                                                        "temp/graphicssvs/winscw_udeb/t_animplugin.dll";
copy $epoc . "release/winscw/udeb/t_fbservapi.exe",                                                         "temp/graphicssvs/winscw_udeb/t_fbservapi.exe";
copy $epoc . "release/winscw/udeb/t_graphicsbitgdiapi.exe",                                                 "temp/graphicssvs/winscw_udeb/t_graphicsbitgdiapi.exe";
copy $epoc . "release/winscw/udeb/t_graphicsfntstoreapi.exe",                                               "temp/graphicssvs/winscw_udeb/t_graphicsfntstoreapi.exe";
copy $epoc . "release/winscw/udeb/t_graphicswservapi.exe",                                                  "temp/graphicssvs/winscw_udeb/t_graphicswservapi.exe";

copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitgc-publicapi-2.ini",                     "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitgc-publicapi-2.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitgc-publicapi-3.ini",                     "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitgc-publicapi-3.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitgc-publicapi.ini",                       "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitgc-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitgc-publicapi.script",                    "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitgc-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitgcfont-publicapi.ini",                   "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitgcfont-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitgcfont-publicapi.script",                "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitgcfont-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitmapdevice-publicapi.ini",                "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitmapdevice-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsbitmapdevice-publicapi.script",             "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsbitmapdevice-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsdevice-publicapi.ini",                      "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsdevice-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsdevice-publicapi.script",                   "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsdevice-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsscreendevice-publicapi.ini",                "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsscreendevice-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-fbsscreendevice-publicapi.script",             "temp/graphicssvs/graphics/general/graphics-bitgdi-fbsscreendevice-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-polygonfiller-publicapi.ini",                  "temp/graphicssvs/graphics/general/graphics-bitgdi-polygonfiller-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-bitgdi-polygonfiller-publicapi.script",               "temp/graphicssvs/graphics/general/graphics-bitgdi-polygonfiller-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-bitmaputil-publicapi.ini",                     "temp/graphicssvs/graphics/general/graphics-fbserv-bitmaputil-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-bitmaputil-publicapi.script",                  "temp/graphicssvs/graphics/general/graphics-fbserv-bitmaputil-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbsbitmap-publicapi.ini",                      "temp/graphicssvs/graphics/general/graphics-fbserv-fbsbitmap-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbsbitmap-publicapi.script",                   "temp/graphicssvs/graphics/general/graphics-fbserv-fbsbitmap-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbscolor256bitmaputil-publicapi.ini",          "temp/graphicssvs/graphics/general/graphics-fbserv-fbscolor256bitmaputil-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbscolor256bitmaputil-publicapi.script",       "temp/graphicssvs/graphics/general/graphics-fbserv-fbscolor256bitmaputil-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbsfont-publicapi.ini",                        "temp/graphicssvs/graphics/general/graphics-fbserv-fbsfont-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbsfont-publicapi.script",                     "temp/graphicssvs/graphics/general/graphics-fbserv-fbsfont-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbssession-publicapi.ini",                     "temp/graphicssvs/graphics/general/graphics-fbserv-fbssession-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbssession-publicapi.script",                  "temp/graphicssvs/graphics/general/graphics-fbserv-fbssession-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbstypefacestore-publicapi.ini",               "temp/graphicssvs/graphics/general/graphics-fbserv-fbstypefacestore-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fbserv-fbstypefacestore-publicapi.script",            "temp/graphicssvs/graphics/general/graphics-fbserv-fbstypefacestore-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fntstore-bitmapfont-publicapi.ini",                   "temp/graphicssvs/graphics/general/graphics-fntstore-bitmapfont-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fntstore-bitmapfont-publicapi.script",                "temp/graphicssvs/graphics/general/graphics-fntstore-bitmapfont-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fntstore-fntstore-publicapi.ini",                     "temp/graphicssvs/graphics/general/graphics-fntstore-fntstore-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fntstore-fntstore-publicapi.script",                  "temp/graphicssvs/graphics/general/graphics-fntstore-fntstore-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fntstore-openfontrasterizercontext-publicapi.ini",    "temp/graphicssvs/graphics/general/graphics-fntstore-openfontrasterizercontext-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-fntstore-openfontrasterizercontext-publicapi.script", "temp/graphicssvs/graphics/general/graphics-fntstore-openfontrasterizercontext-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-anim-publicapi.ini",                            "temp/graphicssvs/graphics/general/graphics-wserv-anim-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-anim-publicapi.script",                         "temp/graphicssvs/graphics/general/graphics-wserv-anim-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animdll-publicapi.ini",                         "temp/graphicssvs/graphics/general/graphics-wserv-animdll-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animdll-publicapi.script",                      "temp/graphicssvs/graphics/general/graphics-wserv-animdll-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animgeneralfunctions-publicapi.ini",            "temp/graphicssvs/graphics/general/graphics-wserv-animgeneralfunctions-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animgeneralfunctions-publicapi.script",         "temp/graphicssvs/graphics/general/graphics-wserv-animgeneralfunctions-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animgfwe-publicapi.ini",                        "temp/graphicssvs/graphics/general/graphics-wserv-animgfwe-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animgfwe-publicapi.script",                     "temp/graphicssvs/graphics/general/graphics-wserv-animgfwe-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animspritefunctions-publicapi.ini",             "temp/graphicssvs/graphics/general/graphics-wserv-animspritefunctions-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animspritefunctions-publicapi.script",          "temp/graphicssvs/graphics/general/graphics-wserv-animspritefunctions-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animwindowfunctions-publicapi.ini",             "temp/graphicssvs/graphics/general/graphics-wserv-animwindowfunctions-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-animwindowfunctions-publicapi.script",          "temp/graphicssvs/graphics/general/graphics-wserv-animwindowfunctions-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-backedupwindow-publicapi.ini",                  "temp/graphicssvs/graphics/general/graphics-wserv-backedupwindow-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-backedupwindow-publicapi.script",               "temp/graphicssvs/graphics/general/graphics-wserv-backedupwindow-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-blankwindow-publicapi.ini",                     "temp/graphicssvs/graphics/general/graphics-wserv-blankwindow-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-blankwindow-publicapi.script",                  "temp/graphicssvs/graphics/general/graphics-wserv-blankwindow-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-directscreenaccess-publicapi.ini",              "temp/graphicssvs/graphics/general/graphics-wserv-directscreenaccess-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-directscreenaccess-publicapi.script",           "temp/graphicssvs/graphics/general/graphics-wserv-directscreenaccess-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-dsasession-publicapi.ini",                      "temp/graphicssvs/graphics/general/graphics-wserv-dsasession-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-dsasession-publicapi.script",                   "temp/graphicssvs/graphics/general/graphics-wserv-dsasession-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-events-publicapi.ini",                          "temp/graphicssvs/graphics/general/graphics-wserv-events-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-events-publicapi.script",                       "temp/graphicssvs/graphics/general/graphics-wserv-events-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-frame-publicapi.ini",                           "temp/graphicssvs/graphics/general/graphics-wserv-frame-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-frame-publicapi.script",                        "temp/graphicssvs/graphics/general/graphics-wserv-frame-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-session-publicapi.ini",                         "temp/graphicssvs/graphics/general/graphics-wserv-session-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-session-publicapi.script",                      "temp/graphicssvs/graphics/general/graphics-wserv-session-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-soundplugin-publicapi.ini",                     "temp/graphicssvs/graphics/general/graphics-wserv-soundplugin-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-soundplugin-publicapi.script",                  "temp/graphicssvs/graphics/general/graphics-wserv-soundplugin-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-window-publicapi.ini",                          "temp/graphicssvs/graphics/general/graphics-wserv-window-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-window-publicapi.script",                       "temp/graphicssvs/graphics/general/graphics-wserv-window-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-windowgc-publicapi.ini",                        "temp/graphicssvs/graphics/general/graphics-wserv-windowgc-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-windowgc-publicapi.script",                     "temp/graphicssvs/graphics/general/graphics-wserv-windowgc-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-windowgroup-publicapi.ini",                     "temp/graphicssvs/graphics/general/graphics-wserv-windowgroup-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-windowgroup-publicapi.script",                  "temp/graphicssvs/graphics/general/graphics-wserv-windowgroup-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsbitmap-publicapi.ini",                        "temp/graphicssvs/graphics/general/graphics-wserv-wsbitmap-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsbitmap-publicapi.script",                     "temp/graphicssvs/graphics/general/graphics-wserv-wsbitmap-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsgraphicbitmap-publicapi.ini",                 "temp/graphicssvs/graphics/general/graphics-wserv-wsgraphicbitmap-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsgraphicbitmap-publicapi.script",              "temp/graphicssvs/graphics/general/graphics-wserv-wsgraphicbitmap-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsgraphicbitmapanimation-publicapi.ini",        "temp/graphicssvs/graphics/general/graphics-wserv-wsgraphicbitmapanimation-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsgraphicbitmapanimation-publicapi.script",     "temp/graphicssvs/graphics/general/graphics-wserv-wsgraphicbitmapanimation-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsgraphicmsgbuf-publicapi.ini",                 "temp/graphicssvs/graphics/general/graphics-wserv-wsgraphicmsgbuf-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsgraphicmsgbuf-publicapi.script",              "temp/graphicssvs/graphics/general/graphics-wserv-wsgraphicmsgbuf-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wspointercursor-publicapi.ini",                 "temp/graphicssvs/graphics/general/graphics-wserv-wspointercursor-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wspointercursor-publicapi.script",              "temp/graphicssvs/graphics/general/graphics-wserv-wspointercursor-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsscreendevice-publicapi.ini",                  "temp/graphicssvs/graphics/general/graphics-wserv-wsscreendevice-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wsscreendevice-publicapi.script",               "temp/graphicssvs/graphics/general/graphics-wserv-wsscreendevice-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wssprite-publicapi.ini",                        "temp/graphicssvs/graphics/general/graphics-wserv-wssprite-publicapi.ini";
copy $epoc . "release/winscw/udeb/z/graphics/graphics-wserv-wssprite-publicapi.script",                     "temp/graphicssvs/graphics/general/graphics-wserv-wssprite-publicapi.script";
copy $epoc . "release/winscw/udeb/z/graphics/t_graphics.ini",                                               "temp/graphicssvs/graphics/general/t_graphics.ini";
copy $epoc . "release/winscw/udeb/z/graphics/t_graphics.tcs",                                               "temp/graphicssvs/graphics/general/t_graphics.tcs";
copy $epoc . "release/winscw/udeb/z/graphics/t_graphics_panic.tcs",                                         "temp/graphicssvs/graphics/general/t_graphics_panic.tcs";

copy $epoc . "release/winscw/udeb/z/graphics/bitgdi/test_rwssprite_bitmap.mbm",                             "temp/graphicssvs/graphics/bitgdi/general/test_rwssprite_bitmap.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/fntstore/bad_entrysel",                                        "temp/graphicssvs/graphics/fntstore/general/bad_entrysel";
copy $epoc . "release/winscw/udeb/z/graphics/fntstore/dummy",                                               "temp/graphicssvs/graphics/fntstore/general/dummy";
copy $epoc . "release/winscw/udeb/z/graphics/fntstore/dummy",                                               "temp/graphicssvs/graphics/fntstore/general/dummy_2";
copy $epoc . "release/winscw/udeb/z/graphics/fntstore/testfontws.gdr",                                      "temp/graphicssvs/graphics/fntstore/general/testfontws.gdr";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/empty_file.txt",                                   "temp/graphicssvs/graphics/t_fbservapi/general/empty_file.txt";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/scaniline_10bytes.txt",                            "temp/graphicssvs/graphics/t_fbservapi/general/scaniline_10bytes.txt";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/testfontfb.gdr",                                   "temp/graphicssvs/graphics/t_fbservapi/general/testfontfb.gdr";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/test_bitmap.mbm",                                  "temp/graphicssvs/graphics/t_fbservapi/general/test_bitmap.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/test_bitmap_24bit_400x300.mbm",                    "temp/graphicssvs/graphics/t_fbservapi/general/test_bitmap_24bit_400x300.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/test_bitmap_32x8.mbm",                             "temp/graphicssvs/graphics/t_fbservapi/general/test_bitmap_32x8.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/test_bitmap_offset8.mbm",                          "temp/graphicssvs/graphics/t_fbservapi/general/test_bitmap_offset8.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/t_fbservapi/test_bitmap_rom.rbm",                              "temp/graphicssvs/graphics/t_fbservapi/general/test_bitmap_rom.rbm";
copy $epoc . "release/winscw/udeb/z/graphics/wserv/testfontws.gdr",                                         "temp/graphicssvs/graphics/wserv/general/testfontws.gdr";
copy $epoc . "release/winscw/udeb/z/graphics/wserv/test_alpha.mbm",                                         "temp/graphicssvs/graphics/wserv/general/test_alpha.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/wserv/test_board.mbm",                                         "temp/graphicssvs/graphics/wserv/general/test_board.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/wserv/test_mask.mbm",                                          "temp/graphicssvs/graphics/wserv/general/test_mask.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/wserv/test_rwssprite_bitmap.mbm",                              "temp/graphicssvs/graphics/wserv/general/test_rwssprite_bitmap.mbm";
copy $epoc . "release/winscw/udeb/z/graphics/wserv/wsgraphicbitmapanimation.mbm",                           "temp/graphicssvs/graphics/wserv/general/wsgraphicbitmapanimation.mbm";

system("7z a -tzip graphicssvs.zip ./temp/*");
